goj:
  security:
    ignore:
      urls:
        - "/practice/classify/**"
        - "/practice/problem/**"
        - "/user/user/login"
        - "/user/user/register"
        - "/user/user/userEmail"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://10.2.6.36:10001/rsa/publicKey'
  main:
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: management-routh
          uri: lb://management
          predicates:
            - Path=/management/**

        - id: practice-routh
          uri: lb://practice
          predicates:
            - Path=/practice/**

        - id: user-routh
          uri: lb://user
          predicates:
            - Path=/user/**

logging:
  level:
    org.springframework.cloud.gateway: debug