spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

## QQ邮箱配置
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1790286512@qq.com #发送邮件的邮箱地址
    password:  nhutydnuwofvejjh #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    port: 465 #端口号465或587
    protocol: smtps